### ISSUE TITLE
Unfinished sentence

### ISSUE THREAD

**Issue by rebeccaestes** [whatisjasongoldstein/buildcss#1]
You cut off the last sentence on the main page: 

`Need a place to write code? You should get used to working with plain html files on your desktop. But you can also`

I'm on the edge of my seat waiting to find out what I can also do :open_mouth:

**Comment by whatisjasongoldstein** [comment]
Fixed in https://github.com/whatisjasongoldstein/buildcss/commit/8933e0378694cc7ad80f4ce6c75740f9eeeb080c
