### ISSUE TITLE
Collapsing margins

### ISSUE THREAD

**Issue by duncanmalashock** [whatisjasongoldstein/buildcss#13]
Great site— thought I'd add this topic as you don't address it. The MDN rundown you link to is pretty brief, and doesn't offer anything helpful around pros & cons of where margins can be assigned to (all on one side? Equally shared between top & bottom?), and how floats can complicate the issue.

**Comment by whatisjasongoldstein** [comment]
That'd be a good addition. Thanks!

**Comment by whatisjasongoldstein** [comment]
Added in the notes of a few different sections where these effects are visible.
