### ISSUE TITLE
Build Shit in JavaScript

### ISSUE THREAD

**Issue by pkafei** [whatisjasongoldstein/buildcss#2]
This is quite a comprehensive guide to CSS. It would be awesome to have a similar resource for JavaScript.

**Comment by whatisjasongoldstein** [comment]
Glad to hear that!

Build Shit in JavaScript is an interesting idea... What might it look like/cover?

**Comment by pkafei** [comment]
A useful JavaScript tutorial would cover beginner debugger strategies (i.e. console,and chrome dev tools) It would also acknowledge there are more advanced ways to debug JS. https://www.youtube.com/watch?v=-q1z8BPFItw

Other topics would include:
- This and scope in JavaScript https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/this
- What problems can't be solved by Jquery and when to dive into vanilla JavaScript
- The goodness of Underscore and why you don't always need a full-blown JS framework http://underscorejs.org/
- JavaScript Prototype-based inheritance 
- Event bubbling

**Comment by whatisjasongoldstein** [comment]
Interesting...

Part of this is within the scope of a more straightforward language book like _Javascript: The Good Parts_ or the John Duckett.

But there is definite a case for "okay, I know all this in pieces, how can I apply it to actually making something more complicated than a button?"

I'll keep thinking about it.

**Comment by pkafei** [comment]
Hey, I happen to find alert boxes and the buttons that control them stimulating to build!

I think it would be cool to write a page with broken JavaScript, and have the person find 7 JS errors. Perhaps you can hide an easter egg or two inside the broken site.

**Comment by tBaxter** [comment]
Similar to "you don't need bootstrap", "you don't need jQuery"

**Comment by tBaxter** [comment]
9 ways your js _will_ fail.

**Comment by whatisjasongoldstein** [comment]
Also: you don't need Angular.

**Comment by whatisjasongoldstein** [comment]
Given what's happened to the javascript world in the last two years I think there's still a case for this, but I'm not taking it on anytime soon.
